### ISSUE TITLE
opencv "Assertion failed" error

### ISSUE THREAD

**Issue by Pejosonic** [fvilmos/tello_object_tracking#2]
When trying to run the example i'm getting this error:
run command:
`
python3 tello_object_tracking.py -proto ./data/ssd_mobilenet_v1_coco_2017_11_17.pbtxt -model ./data/frozen_inference_graph.pb -obj Person -debug True -dconf 0.4`

```

[ERROR:0] global C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-ep71p_ws\opencv\modules\videoio\src\cap.cpp (162) cv::VideoCapture::open VIDEOIO(CV_IMAGES): raised OpenCV exception:

OpenCV(4.5.3) C:\Users\runneradmin\AppData\Local\Temp\pip-req-build-ep71p_ws\opencv\modules\videoio\src\cap_images.cpp:293: error: (-215:Assertion failed) !_filename.empty() in 
function 'cv::CvCapture_Images::open'
```

Maybe is because an opencv version mismatch? Installed opencv-python-4.5.3.56

**Comment by fvilmos** [comment]
At first glance, it seems the application can't connect to the Tello video stream, therefore no image is decoded. If you are connected to the Tello wifi and the problem still persists, please try to install the ffmpeg drivers on your system.
